### ISSUE TITLE
Auto project creation

### ISSUE THREAD

**Issue by fkrauthan** [javiplx/jenkins-gitlab-hook-plugin#56]
I recently tried to turn on the automatic project copy mode. But I always get the error message that it can't find the master project. But if I push to master it finds the project for the master branch and starts building it. Is there more documentation how I have to setup the git repository in my master jenkins job so the plugin can find it?

**Comment by javiplx** [comment]
It is very likely that the reason is that your master project has a wildcard on branch specification. If that is the reason, it will get solved on v1.3.0, that will probably be released this week as I'm doing the final documentation review. In the meantime, if you change it to 'origin/master', it should find the master branch, although you will likely hit some other bug already solved on 1.3

**Comment by fkrauthan** [comment]
I tried a lot configurations. It was always able to find the master branch if it had to build the master project. But all pushes to a different branch ended up with the error can't find master branch. Gonna try it when the update to 1.3 is out.

**Comment by fkrauthan** [comment]
Ok it finds now the correct master project with release 1.3 but I have another issue. If it tries to create the project I get the following error:

NameError - no constructorfor arguments (hudson.security.AccessDeniedException2) on Java::OrgJrubyExceptions::RaiseException:
	/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:59:in `process_projects'
	/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:30:in `POST /build_now'


I think it is related to the fact that I require authentication for my jenkins server.

**Comment by javiplx** [comment]
You are right. I though I have added the _ACL.impersonate_ function, but I didn't. I've fixed, and tried to upload a new version for test it, but maven.jenkins-ci.org seems down. In the meantime, you can build your own hpi from branch _upstream_1.2.1_.

**Comment by javiplx** [comment]
The hpi with the fix is available as [1.3.1-SNAPSHOT](http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/ruby-plugins/gitlab-hook/1.3.1-SNAPSHOT/gitlab-hook-1.3.1-20150223.180605-19.hpi)

**Comment by fkrauthan** [comment]
1.3.1-SNAPSHOT version is working fine for me thanks.
