### ISSUE TITLE
Release of the fixed issue JENKINS-28452

### ISSUE THREAD

**Issue by rlagoue** [javiplx/jenkins-gitlab-hook-plugin#91]
@javiplx 

Just a friendly reminder. You already fixed the issue JENKINS-28452 in the past, and announced it to be in the next release. 
Since many months have passed now, I would like to know when it will be eventually released.

Sincerely
Rodrigue

**Comment by javiplx** [comment]
Already released as 1.4.1.1. It is not yet on update center, but should appear there in a few hours.
